exclude: "docs|node_modules|migrations|.git|.tox"
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending

  - repo: https://gitlab.com/pycqa/flake8
    rev: master
    hooks:
      - id: flake8

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.0 # Use the sha / tag you want to point at
    hooks:
      - id: prettier
